### ISSUE TITLE
`trigger_load` does not find a module with no specified handlers

### ISSUE THREAD

**Issue by xulongwu4** [BirdeeHub/lze#11]
The same result as https://github.com/nvim-neorocks/lz.n/issues/104 even though the `trigger_load()` function of `lze` does not invoke a `lookup` function call.

**Comment by BirdeeHub** [comment]
if no handler is specified it loads at startup.

lze actually handles this case, as it tracks the state itself, rather than the handlers tracking the state for trigger_load.

You would include a spec, and in that spec add `lazy = true` without using any handler fields

This will add it to lze without loading it at startup but no handlers will pick it up, because you didnt use any of their fields.

To load it, you can then just do trigger_load('name')

**Comment by BirdeeHub** [comment]
However, it isnt actually listed in the plugin spec.

Maybe I should add it to the readme?

**Comment by xulongwu4** [comment]
@BirdeeHub Great! I tried it and it worked.

Is the `lazy = true` key mentioned somewhere in the README?

**Comment by BirdeeHub** [comment]
It is not

**Comment by BirdeeHub** [comment]
I should probably do that. along with adding it to the typedef for lze.Spec

**Comment by xulongwu4** [comment]
Thanks. I will go ahead and close the issue then.

**Comment by BirdeeHub** [comment]
Oh, also if you just want to load after another plugin but before its after hook, theres an optional handler specifically for that if you want to add it. the on_plugin handler

But yeah this works just as well. Might even technically be more performant.

**Comment by BirdeeHub** [comment]
https://github.com/BirdeeHub/nixCats-nvim/blob/main/lua/myLuaConf/plugins/completion.lua

The nixCats example config makes good use of that handler though for cmp sources if you wanted an example.

**Comment by BirdeeHub** [comment]
but yeah the `lazy = true` trick is a byproduct of exactly how `lze` differs from `lz.n`

I rewrote the core of `lz.n` such that `lze.c.loader` has the only authoritative copy of the state, which, once entered, cannot be changed.

On the surface this seems to give the handlers less flexibility, but it actually offers more, as now we can safely control global modifications by opening a controlled window for handlers to use before entering it via a callback that happens in a predictable order and manner, and also trigger things without handlers being involved.

Doing this way achieves this without making anything unpredictable, and also makes handlers easier to write, as now you no longer need to be as careful with your state in your handler because you dont have to hold onto the real one.

I think the motivation for the way `lz.n` handles state is good, managing less state is good thing... except, the whole point of the plugin IS to manage the list of plugins to lazily load.

So rather than offloading the state to the handlers meaning "managing less state", it actually just means that your authoritative state is actually now being managed as several copies spread across the handlers? Which also means you NEED a handler because otherwise your spec just dissapears into the GC.

So I think the way I chose to approach it with `lze` is much more realistic about what state `lze` actually does and does not need to manage in its core.

**Comment by BirdeeHub** [comment]
Me and the author of `lz.n` had quite the debate over this point, which lead to the creation of `lze`

**Comment by BirdeeHub** [comment]
it is now mentioned in the readme :)

**Comment by BirdeeHub** [comment]
The way `lz.n` could fix it is probably by introducing like, a no_op handler or something that just holds it until you call trigger load, which is what his suggested workaround more or less achieves.

**Comment by BirdeeHub** [comment]
Looks like he went ahead and did that 😊
