### ISSUE TITLE
Please stop shedding a bad light on lz.n

### ISSUE THREAD

**Issue by mrcjkb** [BirdeeHub/lze#14]
I am fine with you maintaining a fork to serve your own wants, and the license allows that.

But frankly, the misinformation you are spreading about lz.n via your fork's readme, and how you are trying to sell it as an "improvement" (when I've [clearly outlined why the design choices you were proposing for lz.n are not an improvement](https://github.com/nvim-neorocks/lz.n/pull/56)), is quite disturbing and disrespectful.

**Comment by BirdeeHub** [comment]
I think the only place I have talked about lz.n in relation to lze was the PR to nixpkgs, and in the readme. Is there something particular in the readme I should change?

I very much disagree that they are not an improvement. I very much believe that this is, in fact, a big improvement to the ability to extend the plugin, and is good for predictability of effect.

**Comment by BirdeeHub** [comment]
I see 2 things I could do without in the readme actually

**Comment by BirdeeHub** [comment]
Ill change it and you can let me know if its better.

**Comment by BirdeeHub** [comment]
Hopefully this is better?

I strongly believe all the things mentioned are improvements and I will not be saying that they are not. But I can at least remove as many comparisons as possible while still explaining why this repository exists in the first place.

**Comment by mrcjkb** [comment]
> I very much believe that this is, in fact, a big improvement to the ability to extend the plugin, and is good for predictability of effect.

You have stated this belief, but not provided a use case to back it up.
On the other hand, I have previously provided a real world example that demonstrates why multiple sources of state are bad, and explained why lz.n. does not need to care about the order in which handlers are invoked.

> Is there something particular in the readme I should change?

Frankly, I'm disappointed that you're asking me to take the time to outline this for you. But here are some examples:

> lze takes a more flexible approach to the core spec processing, and the managing of handlers, and the managing of how loading is called.

More permissive != more flexible. 
You wanted to allow handlers to be able to do anything. lz.n. sets clear boundaries (to adhere to the liskov substitution and single responsibility principles). If there arises a need to do something that handlers are not suitable for (e.g. adding debugging capabilities or UI), lz.n will provide a separate, clearly defined API for that (which is on the roadmap).
The "two new handlers for dealing with plugins that DON'T follow best practices" are redundant for lz.n, as [outlined here](https://github.com/nvim-neorocks/lz.n?tab=readme-ov-file#plugin-dependencies).

Handlers are there to manage the lazy-loading of plugins. The only added requirement in version 2.0.0 is that they are able to communicate if a plugin is pending to be lazy-loaded by them, which is not a big change if implemented properly.
They have always had to maintain state. In fact, the `add` function always had the single responsibility of updating a handler's state. Doing any additional logic in that function (as you do in some of your handlers) is another violation of the SRP and a potential negative impact on startup performance.
See [the updated example in the wiki](https://github.com/nvim-neorocks/lz.n/wiki/Custom-handler-examples) for instance.

> Handler implementations of even the built-in handlers are now decoupled from the core loading api

At the cost of having multiple sources of state, and coupling the handlers' implementation with their own state management + the core's state management. This is not an improvement, as I have outlined  previously.
It's certainly not a "decoupling". It's just a rewiring of the coupling.
Furthermore, the lz.n implementation is loosely coupled, due to dependency injection.

> It provides a before and after hook

This is just an abstraction, not an improvement.
It's a redundant abstraction, because you already have all the flexibility you need with the `before` and `after` hooks of the plugin spec.

> and also allows abuse of the api to be predictable if absolutely necessary.

Again, the roadmap for lz.n is to provide concrete APIs where necessary. 
Not one abstract API for everything.

**Comment by BirdeeHub** [comment]
As I said, we have a core difference in design philosophy.

I have been using the plugin for a while. I did not get the flexibility I desired with the before and after hooks of the plugin specs.

I proposed as minimal as possible changes to enable them, and then 1 extra one which would be a good feature (the after hook). However I also really wanted to do the other changes I made. ESPECIALLY making it so that trigger_load couldnt take a plugin spec as argument anymore.

And I agree, they are not fully decoupled necessarily, they have hooks that get called by lze, as yours do, and colorscheme 1000 I probably should have not left in there, but it is useful and wont break things with the new design.

However they are in a practical sense fully decoupled now, as they can be completely removed, and they dont have code specific to each handler in the core section of lze anymore.

If multiple sources of state are bad why do you have 5+ of them now chosen at random to provide the core feature of the plugin, the loading hooks.

Any one of those can mess it up by say, merging specs wrong and removing a loading hook, which they may not notice immediately because it only happens if their lookup function is called, which happens in an uncontrolled order.

It also forces them to hold extra items they may not need, when the name would have been sufficient, increasing memory useage (slightly)

And if one of them doesnt delete, its possible that the core reason the change was introduced, idempotency of trigger_load, is not even upheld.

You will not change my mind that this is better. You have made good points in the past and probably will continue to do so, but this is not one of them.

**Comment by BirdeeHub** [comment]
Closed because I thought this was just about me wording things badly but its actually to come here and tell me that my version of the plugin is worse than yours when, I also have clearly stated why this is not the case.

**Comment by BirdeeHub** [comment]
I do like that wording though. I will use the word pemissable

**Comment by BirdeeHub** [comment]
Also I thought UI was out of scope? But you are going to add an entire api for one? I really dont care about UIs all that much for this sort of thing. I will possibly add an alternate load function for loading after dirs when I find a design for one Im happy with. Outside of that lze doesnt exactly have a roadmap for more features, other than better tests.

**Comment by BirdeeHub** [comment]
In short, I see why in some cases, the pattern you decided to use is desireable. But in this case, it is not.

**Comment by BirdeeHub** [comment]
A single source of state that comes from 5 places is not a single source even if its all queried by a single function.

I will stand by my opinion on that because I believe it to be correct.

---

lz.n keeps more than my personal needs in mind. Such as the people asking how to do dependency management in your discussions, which unfortunately is a thing that is sometimes needed, if only to keep things clean.

It does not, however, have a rocks plugin. I will mention that as a positive of lz.n on the readme and attempt one more rewrite of the section that mentions lz.n

I did message you on reddit, which I probably should not have done, my apologies there, I went to chill out and when I opened my browser, the message box where I was already speaking with you was still there and I was upset by the change.

I did not bombard you on multiple github threads, I explained why I thought it was a bad change in a pull request I got CC'd into and asked my opinion. I believe I also commented on the issue about said pull request, which again, I was also CC'd into.

My comments were all about the code change being discussed, none were about you, I still think you are very skilled at what you do.

I only directly say the word improvements 1 time in the readme. I will remove it, and attempt to do a better job of explaining.

**Comment by BirdeeHub** [comment]
Also, yes. You linked my debug handler. Yours can still do that. I haven't used it yet actually it only exists because I wrote it for someone in your issues board who wanted to know what had been loaded.

**Comment by BirdeeHub** [comment]
I am happy to discuss matters of respect, on that note, I have changed the readme again, hopefully it will be at least acceptable.

But I will not be arguing about the positives or negatives of these changes any further. I believed the changes made to be negative, and I stated why I think so, and I believe the ones I made to be an improvement, and have stated why I think so. You have also stated why you believe the opposite. I do not think the explanation is valid, just as you do not find mine to be valid. This is ok. We can disagree.

**Comment by BirdeeHub** [comment]
> Sure, you can reduce the internal state a handler needs to keep track of [by deferring the logic to the add function](https://github.com/BirdeeHub/lze/blob/cf1f2e078f20687a89ad8b3cda8f56a119c4ddf2/lua/lze/h/dep_of.lua#L15). But that's a violation of the SRP and LSP with regard to said add function. Plus said logic is executed at startup time. So you're potentially saving memory at the cost of startup performance (which defeats the purpose of lazy-loading).

This is incorrect. The logic in that add function comes from your parse function which is executed just BEFORE add is called.
This has no more startuptime impact than lz.n does.

**Comment by mrcjkb** [comment]
Blocked.

**Comment by BirdeeHub** [comment]
sure, youre the one leaving comments on my repo now, if doing so upsets you, feel free to do whatever you wish instead.
